version: "3.8"
services:
  ### Postgres Database ###
  postgres:
    image: postgres
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
  ### API Spring Boot ###
  api:
    container_name: bamcorepport_dockerimage
    image: bamcorepport_dockerimage
    build:  ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    ports:
      - "8080:3100"