version: "3.8"
services:
  ### Postgres Database ###
  postgres:
    image: postgres
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: soumia
      POSTGRES_DB: bamDb
    networks:
      - mynet
  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
  ### API Spring Boot ###
  api:
    container_name: bamcorepport_dockerimage
    image: bamcorepport_dockerimage
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bamDb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: soumia
    ports:
      - "8080:3100"
    networks:
      - mynet
networks:
    mynet:
      driver: bridge

#DATABASE_URL: postgresql://postgres:5432/db